### ISSUE TITLE
[winx64] bind IPv6 localhost UDP issue, while TCP works

### ISSUE THREAD

**Issue by Opensourcecommunitydevelopment** [adamyi/v6dns#1]
hello,

i found this helpful. But i experienced problems if trying To bind v6dns On IPv6 localhost.

```

PS C:\> node --version
v4.4.7
PS C:\> v6dns ::1 53 ::1 653 6
v6dns 1.0.5
Lovely presented by adamyi. Under MIT License.
Using configuration:
 { host: '::1',
  port: 53,
  server: '::1',
  serverport: 653,
  priority: 6 }
{ [Error: bind EINVAL ::1:53]
  code: 'EINVAL',
  errno: 'EINVAL',
  syscall: 'bind',
  address: '::1',
  port: 53 }
server listening on { address: '::1', family: 'IPv6', port: 53 }


PS C:\> v6dns [::1] 53 ::1 653 6
v6dns 1.0.5
Lovely presented by adamyi. Under MIT License.
Using configuration:
 { host: '[::1]',
  port: 53,
  server: '::1',
  serverport: 653,
  priority: 6 }
server listening on { address: '::1', family: 'IPv6', port: 53 }
{ [Error: getaddrinfo ENOTFOUND [::1]]
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: '[::1]' }`

```

But Version 4 works Fine:
`PS C:\> v6dns 127.0.0.1 53 ::1 653 6
v6dns 1.0.5
Lovely presented by adamyi. Under MIT License.
Using configuration:
 { host: '127.0.0.1',
  port: 53,
  server: '::1',
  serverport: 653,
  priority: 6 }
server listening on { address: '127.0.0.1', family: 'IPv4', port: 53 }
server listening on { address: '127.0.0.1', family: 'IPv4', port: 53 }`

With the erros above, i still can query Version 6dns over tcp locally On [::1]:53 ! But udp Not. No the port is Not inuse and nodejs got admin privilege.
At the first Look, for me it looks like the „:" port Argument is Not escaped correctly ? How Comes TCP listening works with same Version6dns arguments 

If using „current“ node Version it gives this error:

```

PS C:\> node --version
v6.3.1
PS C:\> v6dns ::1 53 ::1 653 6
v6dns 1.0.5
Lovely presented by adamyi. Under MIT License.
Using configuration:
 { host: '::1',
  port: 53,
  server: '::1',
  serverport: 653,
  priority: 6 }
{ Error: bind EINVAL ::1:53
    at Object.exports._errnoException (util.js:1012:11)
    at exports._exceptionWithHostPort (util.js:1035:20)
    at dgram.js:221:18
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:577:11)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3
  code: 'EINVAL',
  errno: 'EINVAL',
  syscall: 'bind',
  address: '::1',
  port: 53 }
server listening on { address: '::1', family: 'IPv6', port: 53 }
```

**Comment by Opensourcecommunitydevelopment** [comment]
i looked up native-dns and it shows that if listening Online IIPV6 it needs 

```
Server creation

createServer and createUDPServer -- both create a UDP based server, they accept an optional object for configuration,
{ dgram_type: 'udp4' } is the default option, the other is udp6
```
