### ISSUE TITLE
COMMENT - Thanks For The V6DNS Gem!

### ISSUE THREAD

**Issue by GJSmith3rd** [adamyi/v6dns#3]
Just the gem I was looking for while I was battling Google Chromes 300 ms dual stack timer on a high latency (satellite 800+ ms) link. Chrome would always default to IPV4.  V6DNS did just the trick.

**Comment by Opensourcecommunitydevelopment** [comment]
yes on high latency it defaults to ipv4 sadly. chrome works well for you? i sometimes get ERR_NAME_RESOLUTION_FAILED from chrome because it continues query A record and v6dns does reply with empty because website is ipv6enabled ... shit chrome

**Comment by GJSmith3rd** [comment]
Ha ha. It was working great on Chrome for me every time until I tried to configure it to work with DNSMasq. I had it working a few times but tinkering with dnsmasq configs rendered v6dns inoperative.  
:(

I'm on Ubuntu 16.04 LTS. I uninstalled and reinstalled via NPM and removed dnsmasq and reinstalled. If you have any suggestions, thanks in advance.

Yes if Chrome would not try to CHOOSE for you and let you pick a preference of IPV6 or IPV4 all would be good. I'm starting to me the old tech days when companies and developers did not try to make everything easy and fool proof. You can barely configure anything anymore.

**Comment by Opensourcecommunitydevelopment** [comment]
i found a working solution for me with chrome and Force Internet Protocol Version 6 if you don't mind To use google public dns  this may work for you too. but i have Not checked with DNSMasq! If you like to check Let  me know

**Comment by GJSmith3rd** [comment]
Sure - I'd like to check it out (Force Internet Protocol Version 6) but I'd need it to revert to IPv4 on failure because i'm using a HE.net 6in4 tunnel. My ISP does not yet support IPv6.  As I mentioned previously, I'm on a high latency satellite WAN internet link.  Google Chrome's implementation for HappyEyeballs on dual stack machines doesn't work for me because it times out and reverts to IPv4 after 300ms.

**Comment by Opensourcecommunitydevelopment** [comment]
Okay, i have uploaded a Version with preferIPv6 of other nodejs resolver i do like To reference you to here: https://github.com/Opensourcecommunitydevelopment/dns-over-http2
it will always resolve AAAA/IPv6 if available. But if Not like github.com it gives ipv4 address As usual. iam known with hurricane electric tunnels. On My high latency it gives me still ipv6 Website Browsing with chrome. so it works well for me untill now.

Run it like ./dns-over-http2-master>
`node .\index.js 53 127.0.0.1` 
for localhost dns resolver.

this is Experimental Version only. if you find it working or Trouble that is IPv6 related Let me know please. Else the Main Location of it is found here! https://github.com/yyfrankyy/dns-over-http2
you can Check Online Internet Protocol Version preference  easily on sites like this one: http://test-ipv6.com/
in chrome: chrome://net-internals/#dns
may you Want To enable async builtin dnsresolver of chrome. but is optional

**Comment by GJSmith3rd** [comment]
@Opensourcecommunitydevelopment 

OK, I've setup a clone of your code at https://github.com/GJSmith3rd/dns-over-http2 and setup PM2 and adjusted the code a bit for my preferred dev setup (MS VSCode).  I'm getting a unhandled exception 

`
"Cannot find module 'defaultable'"
`
`
"Error: Cannot find module 'defaultable'\n    
    at Function.Module._resolveFilename (module.js:326:15)\n    
    at Function.Module._load (module.js:277:25)\n    at Module.require (module.js:354:17)\n    at require (internal/module.js:12:17)\n    
    at Object.<anonymous> (/home/gjsmith3rd/Workspaces/GIT-Projects/dns-over-http2/dnsd/server.js:5:1)\n    
    at Module._compile (module.js:410:26)\n    at Object.Module._extensions..js (module.js:417:10)\n
    at Module.load (module.js:344:32)\n    at Function.Module._load (module.js:301:12)\n               
    at Module.require (module.js:354:17)"
`

Maybe you can enable issue tracking at https://github.com/Opensourcecommunitydevelopment/dns-over-http2 or comment on an issue at https://github.com/GJSmith3rd/dns-over-http2

I'm currently running node v4.2.6.

Thanks...
`
