### ISSUE TITLE
BUG  ReferenceError: count is not defined

### ISSUE THREAD

**Issue by Opensourcecommunitydevelopment** [adamyi/v6dns#4]
v6dns 1.0.5
node v6.7.0

```
`C:\Users\v6\AppData\Roaming\npm\node_modules\v6dns\node_modules\native-dns-packet\packet.js:497
        throw e;
        ^

ReferenceError: count is not defined
    at writeTruncate (C:\Users\v6\AppData\Roaming\npm\node_modules\v6dns\node_modules\native-dns-packet\packet.js:223:
22)
    at Function.Packet.write (C:\Users\v6\AppData\Roaming\npm\node_modules\v6dns\node_modules\native-dns-packet\packet
.js:416:19)
    at Packet.send (C:\Users\v6\AppData\Roaming\npm\node_modules\v6dns\node_modules\native-dns\lib\packet.js:43:16)
    at C:\Users\v6\AppData\Roaming\npm\node_modules\v6dns\v6dns.js:27:41
    at C:\Users\v6\AppData\Roaming\npm\node_modules\v6dns\node_modules\async\dist\async.js:3679:13
    at C:\Users\v6\AppData\Roaming\npm\node_modules\v6dns\node_modules\async\dist\async.js:486:20
    at replenish (C:\Users\v6\AppData\Roaming\npm\node_modules\v6dns\node_modules\async\dist\async.js:879:29)
    at iterateeCallback (C:\Users\v6\AppData\Roaming\npm\node_modules\v6dns\node_modules\async\dist\async.js:869:21)
    at C:\Users\v6\AppData\Roaming\npm\node_modules\v6dns\node_modules\async\dist\async.js:847:20
    at .<anonymous> (C:\Users\v6\AppData\Roaming\npm\node_modules\v6dns\node_modules\async\dist\async.js:3676:17)`
```

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
```
v6dns    | ReferenceError: count is not defined
v6dns    |     at writeTruncate (/root/.npm/lib/node_modules/v6dns/node_modules/native-dns/node_modules/native-dns-packet/packet.js:223:22)
v6dns    |     at Function.Packet.write (/root/.npm/lib/node_modules/v6dns/node_modules/native-dns/node_modules/native-dns-packet/packet.js:416:19)
v6dns    |     at module.exports.Packet.send (/root/.npm/lib/node_modules/v6dns/node_modules/native-dns/lib/packet.js:43:16)
v6dns    |     at /root/.npm/lib/node_modules/v6dns/v6dns.js:27:41
v6dns    |     at /root/.npm/lib/node_modules/v6dns/node_modules/async/dist/async.js:3888:9
v6dns    |     at /root/.npm/lib/node_modules/v6dns/node_modules/async/dist/async.js:473:16
v6dns    |     at replenish (/root/.npm/lib/node_modules/v6dns/node_modules/async/dist/async.js:1006:25)
v6dns    |     at iterateeCallback (/root/.npm/lib/node_modules/v6dns/node_modules/async/dist/async.js:995:17)
v6dns    |     at /root/.npm/lib/node_modules/v6dns/node_modules/async/dist/async.js:969:16
v6dns    |     at exports.Request.<anonymous> (/root/.npm/lib/node_modules/v6dns/node_modules/async/dist/async.js:3885:13)
```
